CREATE TABLE terms (term_lc varchar(20), term_cap1 varchar(20), key varchar(20), language varchar(20));
INPUT INTO terms VALUES ("nazione", "Nazione", "nation, people", "Latin");
INPUT INTO terms VALUES ("popolo", "Popolo", "nation, people", "Latin");
INPUT INTO terms VALUES ("natio", "Natio", "nation, people", "Spanish");
INPUT INTO terms VALUES ("poplus", "Poplus", "nation, people", "Spanish");
INPUT INTO terms VALUES ("popli", "Popli", "nation, people", "Spanish");
INPUT INTO terms VALUES ("nation", "Nation", "nation, people", "Spanish");
INPUT INTO terms VALUES ("popul", "Popul", "nation, people", "Spanish");
INPUT INTO terms VALUES ("popular", "Popular", "nation, people", "Dutch");
INPUT INTO terms VALUES ("national", "National", "nation, people", "Dutch");
INPUT INTO terms VALUES ("people", "People", "nation, people", "Dutch");
INPUT INTO terms VALUES ("nation", "Nation", "nation, people", "Dutch");
INPUT INTO terms VALUES ("peuple", "Peuple", "nation, people", "German");
INPUT INTO terms VALUES ("gens", "Gens", "nation, people", "German");
INPUT INTO terms VALUES ("nation", "Nation", "nation, people", "German");
INPUT INTO terms VALUES ("nation, people", "Nation, people", "nation, people", "English");
INPUT INTO terms VALUES ("natie", "Natie", "nation, people", "French");
INPUT INTO terms VALUES ("nationaal", "Nationaal", "nation, people", "French");
INPUT INTO terms VALUES ("volk", "Volk", "nation, people", "French");
INPUT INTO terms VALUES ("populair", "Populair", "nation, people", "French");
INPUT INTO terms VALUES ("bevolking", "Bevolking", "nation, people", "French");
INPUT INTO terms VALUES ("gemeenschap", "Gemeenschap", "nation, people", "French");
INPUT INTO terms VALUES ("völkisch", "Völkisch", "nation, people", "Italian");
INPUT INTO terms VALUES ("volk", "Volk", "nation, people", "Italian");
INPUT INTO terms VALUES ("rivoluzione", "Rivoluzione", "revolution", "Latin");
INPUT INTO terms VALUES ("revolution", "Revolution", "revolution", "Dutch");
INPUT INTO terms VALUES ("revolution", "Revolution", "revolution", "German");
INPUT INTO terms VALUES ("revolution", "Revolution", "revolution", "English");
INPUT INTO terms VALUES ("revolutie", "Revolutie", "revolution", "French");
INPUT INTO terms VALUES ("umstuerze", "Umstuerze", "revolution", "Italian");
INPUT INTO terms VALUES ("umstürze", "Umstürze", "revolution", "Italian");
INPUT INTO terms VALUES ("revolution", "Revolution", "revolution", "Italian");
INPUT INTO terms VALUES ("umsturz", "Umsturz", "revolution", "Italian");
INPUT INTO terms VALUES ("violenza", "Violenza", "violence", "Latin");
INPUT INTO terms VALUES ("violentia", "Violentia", "violence", "Spanish");
INPUT INTO terms VALUES ("violence", "Violence", "violence", "Dutch");
INPUT INTO terms VALUES ("violence", "Violence", "violence", "German");
INPUT INTO terms VALUES ("violence", "Violence", "violence", "English");
INPUT INTO terms VALUES ("geweld", "Geweld", "violence", "French");
INPUT INTO terms VALUES ("gewalt", "Gewalt", "violence", "Italian");
INPUT INTO terms VALUES ("giustizia", "Giustizia", "justice", "Latin");
INPUT INTO terms VALUES ("giudice", "Giudice", "justice", "Latin");
INPUT INTO terms VALUES ("justitia", "Justitia", "justice", "Spanish");
INPUT INTO terms VALUES ("justice", "Justice", "justice", "Dutch");
INPUT INTO terms VALUES ("justice", "Justice", "justice", "German");
INPUT INTO terms VALUES ("justice", "Justice", "justice", "English");
INPUT INTO terms VALUES ("gerechtigheid", "Gerechtigheid", "justice", "French");
INPUT INTO terms VALUES ("gerechtigkeit", "Gerechtigkeit", "justice", "Italian");
INPUT INTO terms VALUES ("gerecht", "Gerecht", "justice", "Italian");
INPUT INTO terms VALUES ("scienze", "Scienze", "science", "Latin");
INPUT INTO terms VALUES ("scienza", "Scienza", "science", "Latin");
INPUT INTO terms VALUES ("scientia", "Scientia", "science", "Spanish");
INPUT INTO terms VALUES ("science", "Science", "science", "Dutch");
INPUT INTO terms VALUES ("science", "Science", "science", "German");
INPUT INTO terms VALUES ("science", "Science", "science", "English");
INPUT INTO terms VALUES ("wetenschap", "Wetenschap", "science", "French");
INPUT INTO terms VALUES ("wissenschaft", "Wissenschaft", "science", "Italian");
INPUT INTO terms VALUES ("monarca", "Monarca", "monarchy", "Latin");
INPUT INTO terms VALUES ("monarchia", "Monarchia", "monarchy", "Spanish");
INPUT INTO terms VALUES ("monarch", "Monarch", "monarchy", "Dutch");
INPUT INTO terms VALUES ("monarchy", "Monarchy", "monarchy", "Dutch");
INPUT INTO terms VALUES ("monarchie", "Monarchie", "monarchy", "German");
INPUT INTO terms VALUES ("monarchy", "Monarchy", "monarchy", "English");
INPUT INTO terms VALUES ("monarch", "Monarch", "monarchy", "French");
INPUT INTO terms VALUES ("monarchie", "Monarchie", "monarchy", "French");
INPUT INTO terms VALUES ("monarchie", "Monarchie", "monarchy", "Italian");
INPUT INTO terms VALUES ("italian", "Italian", "Keys", "Latin");
INPUT INTO terms VALUES ("latin", "Latin", "Keys", "Spanish");
INPUT INTO terms VALUES ("english", "English", "Keys", "Dutch");
INPUT INTO terms VALUES ("french", "French", "Keys", "German");
INPUT INTO terms VALUES ("keys", "Keys", "Keys", "English");
INPUT INTO terms VALUES ("dutch", "Dutch", "Keys", "French");
INPUT INTO terms VALUES ("german", "German", "Keys", "Italian");
INPUT INTO terms VALUES ("stato", "Stato", "state", "Latin");
INPUT INTO terms VALUES ("civitat", "Civitat", "state", "Spanish");
INPUT INTO terms VALUES ("civitas", "Civitas", "state", "Spanish");
INPUT INTO terms VALUES ("states", "States", "state", "Dutch");
INPUT INTO terms VALUES ("state", "State", "state", "Dutch");
INPUT INTO terms VALUES ("etat", "Etat", "state", "German");
INPUT INTO terms VALUES ("etats", "Etats", "state", "German");
INPUT INTO terms VALUES ("état", "État", "state", "German");
INPUT INTO terms VALUES ("états", "États", "state", "German");
INPUT INTO terms VALUES ("state", "State", "state", "English");
INPUT INTO terms VALUES ("staat", "Staat", "state", "French");
INPUT INTO terms VALUES ("staat", "Staat", "state", "Italian");
INPUT INTO terms VALUES ("staatlich", "Staatlich", "state", "Italian");
INPUT INTO terms VALUES ("staats", "Staats", "state", "Italian");
INPUT INTO terms VALUES ("diritto", "Diritto", "right", "Latin");
INPUT INTO terms VALUES ("legittimo", "Legittimo", "right", "Latin");
INPUT INTO terms VALUES ("diritti", "Diritti", "right", "Latin");
INPUT INTO terms VALUES ("iure", "Iure", "right", "Spanish");
INPUT INTO terms VALUES ("ius", "Ius", "right", "Spanish");
INPUT INTO terms VALUES ("iura", "Iura", "right", "Spanish");
INPUT INTO terms VALUES ("iuris", "Iuris", "right", "Spanish");
INPUT INTO terms VALUES ("right", "Right", "right", "Dutch");
INPUT INTO terms VALUES ("rightful", "Rightful", "right", "Dutch");
INPUT INTO terms VALUES ("rights", "Rights", "right", "Dutch");
INPUT INTO terms VALUES ("droite", "Droite", "right", "German");
INPUT INTO terms VALUES ("droit", "Droit", "right", "German");
INPUT INTO terms VALUES ("right", "Right", "right", "English");
INPUT INTO terms VALUES ("recht", "Recht", "right", "French");
INPUT INTO terms VALUES ("rechten", "Rechten", "right", "French");
INPUT INTO terms VALUES ("rechtmatig", "Rechtmatig", "right", "French");
INPUT INTO terms VALUES ("rechte", "Rechte", "right", "Italian");
INPUT INTO terms VALUES ("rechtes", "Rechtes", "right", "Italian");
INPUT INTO terms VALUES ("recht", "Recht", "right", "Italian");
INPUT INTO terms VALUES ("rechten", "Rechten", "right", "Italian");
INPUT INTO terms VALUES ("rechts", "Rechts", "right", "Italian");
INPUT INTO terms VALUES ("confederazione", "Confederazione", "republic", "Latin");
INPUT INTO terms VALUES ("repubblica", "Repubblica", "republic", "Latin");
INPUT INTO terms VALUES ("re publica", "Re publica", "republic", "Spanish");
INPUT INTO terms VALUES ("rei publicae", "Rei publicae", "republic", "Spanish");
INPUT INTO terms VALUES ("rerumpublicarum", "Rerumpublicarum", "republic", "Spanish");
INPUT INTO terms VALUES ("rerum publicarum", "Rerum publicarum", "republic", "Spanish");
INPUT INTO terms VALUES ("respublica", "Respublica", "republic", "Spanish");
INPUT INTO terms VALUES ("rebuspublicis", "Rebuspublicis", "republic", "Spanish");
INPUT INTO terms VALUES ("reipublicae", "Reipublicae", "republic", "Spanish");
INPUT INTO terms VALUES ("rem publicam", "Rem publicam", "republic", "Spanish");
INPUT INTO terms VALUES ("rempublicam", "Rempublicam", "republic", "Spanish");
INPUT INTO terms VALUES ("rebus publicis", "Rebus publicis", "republic", "Spanish");
INPUT INTO terms VALUES ("res publicas", "Res publicas", "republic", "Spanish");
INPUT INTO terms VALUES ("res publica", "Res publica", "republic", "Spanish");
INPUT INTO terms VALUES ("republica", "Republica", "republic", "Spanish");
INPUT INTO terms VALUES ("respublicas", "Respublicas", "republic", "Spanish");
INPUT INTO terms VALUES ("commonwealth", "Commonwealth", "republic", "Dutch");
INPUT INTO terms VALUES ("republic", "Republic", "republic", "Dutch");
INPUT INTO terms VALUES ("communauté", "Communauté", "republic", "German");
INPUT INTO terms VALUES ("république", "République", "republic", "German");
INPUT INTO terms VALUES ("republic", "Republic", "republic", "English");
INPUT INTO terms VALUES ("gemenebest", "Gemenebest", "republic", "French");
INPUT INTO terms VALUES ("republiek", "Republiek", "republic", "French");
INPUT INTO terms VALUES ("gemeinwesen", "Gemeinwesen", "republic", "Italian");
INPUT INTO terms VALUES ("republik", "Republik", "republic", "Italian");
INPUT INTO terms VALUES ("re", "Re", "king, queen", "Latin");
INPUT INTO terms VALUES ("regina", "Regina", "king, queen", "Latin");
INPUT INTO terms VALUES ("rex", "Rex", "king, queen", "Spanish");
INPUT INTO terms VALUES ("rege", "Rege", "king, queen", "Spanish");
INPUT INTO terms VALUES ("regium", "Regium", "king, queen", "Spanish");
INPUT INTO terms VALUES ("regina", "Regina", "king, queen", "Spanish");
INPUT INTO terms VALUES ("regis", "Regis", "king, queen", "Spanish");
INPUT INTO terms VALUES ("king", "King", "king, queen", "Dutch");
INPUT INTO terms VALUES ("queen", "Queen", "king, queen", "Dutch");
INPUT INTO terms VALUES ("roi", "Roi", "king, queen", "German");
INPUT INTO terms VALUES ("reine", "Reine", "king, queen", "German");
INPUT INTO terms VALUES ("king, queen", "King, queen", "king, queen", "English");
INPUT INTO terms VALUES ("koningin", "Koningin", "king, queen", "French");
INPUT INTO terms VALUES ("koning", "Koning", "king, queen", "French");
INPUT INTO terms VALUES ("koenig", "Koenig", "king, queen", "Italian");
INPUT INTO terms VALUES ("könig", "König", "king, queen", "Italian");
INPUT INTO terms VALUES ("königin", "Königin", "king, queen", "Italian");
INPUT INTO terms VALUES ("legge", "Legge", "law", "Latin");
INPUT INTO terms VALUES ("diritto", "Diritto", "law", "Latin");
INPUT INTO terms VALUES ("legale", "Legale", "law", "Latin");
INPUT INTO terms VALUES ("lex", "Lex", "law", "Spanish");
INPUT INTO terms VALUES ("leges", "Leges", "law", "Spanish");
INPUT INTO terms VALUES ("law", "Law", "law", "Dutch");
INPUT INTO terms VALUES ("legal", "Legal", "law", "Dutch");
INPUT INTO terms VALUES ("loi", "Loi", "law", "German");
INPUT INTO terms VALUES ("lois", "Lois", "law", "German");
INPUT INTO terms VALUES ("law", "Law", "law", "English");
INPUT INTO terms VALUES ("legaal", "Legaal", "law", "French");
INPUT INTO terms VALUES ("recht", "Recht", "law", "French");
INPUT INTO terms VALUES ("wettelijk", "Wettelijk", "law", "French");
INPUT INTO terms VALUES ("l’illuminismo", "L’illuminismo", "Enlightenment", "Latin");
INPUT INTO terms VALUES ("il secolo dei lumi", "Il secolo dei lumi", "Enlightenment", "Latin");
INPUT INTO terms VALUES ("lumi", "Lumi", "Enlightenment", "Latin");
INPUT INTO terms VALUES ("enlightenment", "Enlightenment", "Enlightenment", "Dutch");
INPUT INTO terms VALUES ("siècle des lumières", "Siècle des lumières", "Enlightenment", "German");
INPUT INTO terms VALUES ("lumière", "Lumière", "Enlightenment", "German");
INPUT INTO terms VALUES ("enlightenment", "Enlightenment", "Enlightenment", "English");
INPUT INTO terms VALUES ("verlichting", "Verlichting", "Enlightenment", "French");
INPUT INTO terms VALUES ("aufklaerung", "Aufklaerung", "Enlightenment", "Italian");
INPUT INTO terms VALUES ("aufklärung", "Aufklärung", "Enlightenment", "Italian");
INPUT INTO terms VALUES ("filosofia", "Filosofia", "philosophy", "Latin");
INPUT INTO terms VALUES ("philosophy", "Philosophy", "philosophy", "Dutch");
INPUT INTO terms VALUES ("philosophie", "Philosophie", "philosophy", "German");
INPUT INTO terms VALUES ("philosophy", "Philosophy", "philosophy", "English");
INPUT INTO terms VALUES ("filosofie", "Filosofie", "philosophy", "French");
INPUT INTO terms VALUES ("philosophie", "Philosophie", "philosophy", "Italian");
